apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kafka-ingress
  namespace: kafka
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "TCP"
    nginx.ingress.kubernetes.io/tcp-services-configmap: "kafka/tcp-services"
spec:
  ingressClassName: nginx
  rules:
  - host: kafka.nks.stjeong.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kafka
            port:
              number: 9092
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: kafka
data:
  "9092": "kafka/kafka:9092"
  "9093": "kafka/kafka-1:9093"
  "9094": "kafka/kafka-2:9094"