apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-broker
  namespace: kafka
spec:
  serviceName: kafka-broker-headless
  replicas: 3
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      containers:
      - name: broker
        image: apache/kafka:4.0.1-rc0
        ports:
        - containerPort: 9092
          name: client
        - containerPort: 19092
          name: internal
        env:
        - name: KAFKA_PROCESS_ROLES
          value: "broker"
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: "0@kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local:29093,1@kafka-controller-1.kafka-controller-headless.kafka.svc.cluster.local:29093,2@kafka-controller-2.kafka-controller-headless.kafka.svc.cluster.local:29093"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT_HOST://:9092,PLAINTEXT://:19092"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "PLAINTEXT"
        - name: CLUSTER_ID
          value: "4L6g3nShT-eMCtK--X86sw"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: "0"
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "2"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_LOG_DIRS
          value: "/var/lib/kafka/data"
        - name: KAFKA_DEFAULT_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_MIN_INSYNC_REPLICAS
          value: "2"
        command:
        - sh
        - -c
        - |
          export KAFKA_NODE_ID=$((${HOSTNAME##*-} + 3))
          export KAFKA_ADVERTISED_LISTENERS="PLAINTEXT_HOST://kafka.nks.stjeong.com:$((9092 + ${HOSTNAME##*-})),PLAINTEXT://${HOSTNAME}.kafka-broker-headless.kafka.svc.cluster.local:19092"
          echo "Starting Kafka broker with NODE_ID=$KAFKA_NODE_ID"
          echo "ADVERTISED_LISTENERS=$KAFKA_ADVERTISED_LISTENERS"
          # Create a config override file
          cat <<EOF > /tmp/broker.properties
          # Basic broker properties
          process.roles=broker
          node.id=$KAFKA_NODE_ID
          controller.quorum.voters=${KAFKA_CONTROLLER_QUORUM_VOTERS}
          controller.listener.names=CONTROLLER
          listeners=${KAFKA_LISTENERS}
          advertised.listeners=$KAFKA_ADVERTISED_LISTENERS
          listener.security.protocol.map=${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
          inter.broker.listener.name=${KAFKA_INTER_BROKER_LISTENER_NAME}
          log.dirs=${KAFKA_LOG_DIRS}
          # Replication settings
          offsets.topic.replication.factor=${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
          transaction.state.log.replication.factor=${KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR}
          transaction.state.log.min.isr=${KAFKA_TRANSACTION_STATE_LOG_MIN_ISR}
          default.replication.factor=${KAFKA_DEFAULT_REPLICATION_FACTOR}
          min.insync.replicas=${KAFKA_MIN_INSYNC_REPLICAS}
          group.initial.rebalance.delay.ms=${KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS}
          EOF
          # Format storage if needed
          if [ ! -f /var/lib/kafka/data/meta.properties ]; then
            /opt/kafka/bin/kafka-storage.sh format -t ${CLUSTER_ID} -c /tmp/broker.properties --ignore-formatted
          fi
          exec /opt/kafka/bin/kafka-server-start.sh /tmp/broker.properties
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: kafka-data
          mountPath: /var/lib/kafka/data
        livenessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 30
          periodSeconds: 10
  volumeClaimTemplates:
  - metadata:
      name: kafka-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 20Gi